In [2]:
    weight_kg = 55
print(weight_kg)

55


In [3]:
print("weight in pounds: ", 2.2 * weight_kg)

weight in pounds:  121.00000000000001


In [4]:
weight_kg = 57.4
print("weight in kg is now", weight_kg)

weight in kg is now 57.4


In [6]:
weight_lb = 2.2 *weight_kg
print("weight in pounds is", weight_lb, "and in kg", weight_kg)

weight in pounds is 126.28 and in kg 57.4


In [8]:
weight_kg = 100

In [9]:
print("weight in pounds is", weight_lb, "and in kg", weight_kg)

weight in pounds is 126.28 and in kg 100


In [19]:
mass = 47.5
age = 122
mass = mass * 2.0
age = age -20
print("mass:", mass, "age:", age)

mass: 95.0 age: 102


In [17]:
## Liabries

In [6]:
import numpy

In [15]:
numpy.loadtxt(fname='data/inflammation-01.csv', delimiter=',')

array([[0., 0., 1., ..., 3., 0., 0.],
       [0., 1., 2., ..., 1., 0., 1.],
       [0., 1., 1., ..., 2., 1., 1.],
       ...,
       [0., 1., 1., ..., 1., 1., 1.],
       [0., 0., 0., ..., 0., 2., 0.],
       [0., 0., 1., ..., 1., 1., 0.]])

In [10]:
import os
print(os.getcwd())

C:\Users\dacai\Desktop\learningPython


In [17]:
data = numpy.loadtxt(fname='data/inflammation-01.csv', delimiter=',')

In [18]:
print(data)

[[0. 0. 1. ... 3. 0. 0.]
 [0. 1. 2. ... 1. 0. 1.]
 [0. 1. 1. ... 2. 1. 1.]
 ...
 [0. 1. 1. ... 1. 1. 1.]
 [0. 0. 0. ... 0. 2. 0.]
 [0. 0. 1. ... 1. 1. 0.]]


In [19]:
print(type(data))

<class 'numpy.ndarray'>


In [20]:
data.shape

(60, 40)

In [21]:
data.dtype

dtype('float64')

In [31]:
##Indexing##

In [24]:
print('First value in data:' , data[0,0])

First value in data: 0.0


In [25]:
print(data[0:4, 0:10])

[[0. 0. 1. 3. 1. 2. 4. 7. 8. 3.]
 [0. 1. 2. 1. 2. 1. 3. 2. 2. 6.]
 [0. 1. 1. 3. 3. 2. 6. 2. 5. 9.]
 [0. 0. 2. 0. 4. 2. 2. 1. 6. 7.]]


In [26]:
print(data[5:10, 0:10])

[[0. 0. 1. 2. 2. 4. 2. 1. 6. 4.]
 [0. 0. 2. 2. 4. 2. 2. 5. 5. 8.]
 [0. 0. 1. 2. 3. 1. 2. 3. 5. 3.]
 [0. 0. 0. 3. 1. 5. 6. 5. 5. 8.]
 [0. 1. 1. 2. 1. 3. 5. 3. 5. 8.]]


In [27]:
print(data[:3, 36:])

[[2. 3. 0. 0.]
 [1. 1. 0. 1.]
 [2. 2. 1. 1.]]


In [36]:
element = "oxygen"
print(element[1:4])

xyg


In [37]:
print(element[:])

oxygen


In [38]:
print(element[3])

g


In [39]:
#operations#

In [28]:
double_data = data * 2.0
print('original:')
print(data[:3,36:])
print(double_data[:3, 36:])

original:
[[2. 3. 0. 0.]
 [1. 1. 0. 1.]
 [2. 2. 1. 1.]]
[[4. 6. 0. 0.]
 [2. 2. 0. 2.]
 [4. 4. 2. 2.]]


In [29]:
triple_data = double_data + data
print("triple_data:")
print(triple_data[:3, 36:])

triple_data:
[[6. 9. 0. 0.]
 [3. 3. 0. 3.]
 [6. 6. 3. 3.]]


#Methods of a numpy array#

In [30]:
print(data.mean())

6.14875


In [34]:
print("maxixmum infammation: ",data.max())
print("minimum infammation: ", data.min())
print("sandard deviation:", data.std())

maxixmum infammation:  20.0
minimum infammation:  0.0
sandard deviation: 4.613833197118566


In [33]:
patient_o = data[ 0, :]
print("the maximum inlammation for patient_1:", data[1, :].max())

the maximum inlammation for patient_1: 18.0


In [35]:
print(data.mean(axis=0))

[ 0.          0.45        1.11666667  1.75        2.43333333  3.15
  3.8         3.88333333  5.23333333  5.51666667  5.95        5.9
  8.35        7.73333333  8.36666667  9.5         9.58333333 10.63333333
 11.56666667 12.35       13.25       11.96666667 11.03333333 10.16666667
 10.          8.66666667  9.15        7.25        7.33333333  6.58333333
  6.06666667  5.95        5.11666667  3.6         3.3         3.56666667
  2.48333333  1.5         1.13333333  0.56666667]


In [36]:
print(data.max)

<built-in method max of numpy.ndarray object at 0x000002C2B4A1F990>


#visualiasion#

In [ ]:
import numpy as np
import matplotlib.pyplot as plt

data = np.loadtxt(fname='data/inflammation-01.csv',delimiter=',')

figure = plt.figure(figsize=(10,3))

axes1 = figure.add_subplot(1, 3, 1)
axes2 = figure.add_subplot(1, 3, 2)
axes3 = figure.add_subplot(1, 3, 3)

